version: "3"

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - '27017:27017'

  tg-bot:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: bot
    environment:
      PATH: /
    command: bot
    restart: always
    network_mode: host
    volumes:
      - ./config.yaml:/config.yaml
      - ./assets/:/assets/
